### PR TITLE
Update utils.py for Python 3

### PR DESCRIPTION
**Pull request by JonathanRoach**

### CODE REVIEW

**Comment by lamby** [comment]
This would appear to break compatibility with Python 2.x which seems essential to keep right now.

**Comment by JonathanRoach** [comment]
Yes, I agree. I haven’t yet investigated ‘best practice’ for supporting 2.x and 3.x, which is why I think my pull request should be kept as an ‘FYI’ for the moment. 

PS, I’m also composing a reply to your last email, which will be with you soon.

Thanks,
Jon

**Comment by lamby** [comment]
You are looking for https://pythonhosted.org/six/ :)

**Comment by JonathanRoach** [comment]
Great link - I’ll get working and submit a new version when ready (there might be a little lead time - there’s a few plates spinning ATM).

Cheers,
Jon

**Comment by lamby** [comment]
Thanks!

**Comment by lamby** [comment]
Please see `master` branch - I needed to make more changes

**Pull request merged**
